site_name: Cours de programmation en sciences
repo_url: https://github.com/profdenis/ProgSciences

theme:
  name: readthedocs
  locale: fr
  color_mode: auto
  user_color_mode_toggle: true

extra_css:
  - style.css

markdown_extensions:
  smarty: { }
  toc:
    permalink: true
  sane_lists: { }
  admonition: { }
  codehilite: { }
  pymdownx.superfences: { }
  pymdownx.fancylists: { }
  pymdownx.saneheaders: { }
  pymdownx.mark: { }
  pymdownx.tabbed: { }
  pymdownx.tasklist: { }
  pymdownx.tilde: { }
  pymdownx.details: { }
  pymdownx.arithmatex:
    generic: true

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

